### ISSUE TITLE
Can't build project when installing via Cocoapods

### ISSUE THREAD

**Issue by chaselal** [MindscapeHQ/raygun4apple#38]
Xcode produces this build error when I try to use `raygun4apple` version 1.4.0 installed via Cocoapods:

```
raygun4apple Group
Lexical or Preprocessor Issue Group
/Users/chase/company/repo/projects/mobile/ios/Pods/Flipper-Folly/folly/Demangle.h:19:10: 'folly/FBString.h' file not found
/Users/chase/company/repo/projects/mobile/ios/Pods/raygun4apple/Sources/KSCrash/Recording/Tools/KSDemangle_Swift.cpp:28:10: In file included from /Users/chase/company/repo/projects/mobile/ios/Pods/raygun4apple/Sources/KSCrash/Recording/Tools/KSDemangle_Swift.cpp:28:
```

the referenced line 28 is `#include "Demangle.h"`

My project is a React Native version 0.62.2 app.

The same happens whether my `Podfile` contains `pod raygun4apple` or `pod 'raygun4apple', :git => 'https://github.com/MindscapeHQ/raygun4apple.git', :tag => '1.4.0'`

**Comment by chaselal** [comment]
I think the problem is another pod, `Flipper-Folly`, includes a file named `Demangle.h` and the compiler tries to resolve the wrong `Demangle.h` in the `KSCrash` source files. I have approximately zero experience with Cocoapods, so I don't know if this is an issue that can be fixed on the pod's side or if it's a matter of my project being set up correctly.

**Comment by mduncan26** [comment]
Hi @chaselal,

Thank you getting in touch. We are aware of this issue and have a [PR](https://github.com/MindscapeHQ/raygun4apple/pull/37) looking to address this problem. We are hoping to have this PR merged and released by the end of next week. I will update this thread once the changes are available.

Thank you,
Mitchell.

**Comment by mduncan26** [comment]
Hi @chaselal,

We have just released an update to our Raygun4Apple pod, version 1.4.1. This includes an update to resolve the compilation issues with other external sources and our library. Please try updating and let me know if your issue has been resolved.

Thank you,
Mitchell.

**Comment by chaselal** [comment]
@mduncan26 The update solved my problem. ✔️ Thanks for your correspondence.
