### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by klm1** [MindscapeHQ/raygun4apple#43]
Please consider adding support for the [Swift Package Manager](https://developer.apple.com/documentation/xcode/creating_a_standalone_swift_package_with_xcode) as an alternative to *CocoaPods*. Packages can contain both Objective C and Swift code.

**Comment by mduncan26** [comment]
Hi @klm1 

Thank you for raising this support ticket. We will take this under consideration for future releases of the provider. I will update this thread when there has been more movement on this topic.

All the best,
Mitchell.

**Comment by spicymatt** [comment]
Come'on...after 1.5yrs still no support for it ?

**Comment by ZhengRaygun** [comment]
Hi @spicymatt, thanks for getting in touch, we appreciate that it is frustrating not having this support after so long. It is sitting in our backlog weighted against other priorities. I've given it a bump to our team who's responsible for this area and see if we could get this supported in the short term. I will loop back and give an update once they've had a chance to review their options.

Thanks for your patience and understanding.

Zheng Li
VP of Product 
Raygun

**Comment by darcythomas** [comment]
Hi @spicymatt,
My name is Darcy I am one of the Engineers here at Raygun.

I am in the process of rolling this out.
I'll let you know once it has all been completed.

**Comment by spicymatt** [comment]
Hello
Thanks a lot for your support…We’ll be trying it out when it comes out.

Matthieu

**Comment by Callum-McKay** [comment]
Hi @klm1, and @spicymatt 

We have released support for the swift package manager as of [version 2.0.0](https://github.com/MindscapeHQ/raygun4apple/releases/tag/2.0.0)

Thanks for your patience, and let me know if you run into any issues with installation and/or setup.

All the best,
Callum.
