### ISSUE TITLE
Server-side Swift / Linux support

### ISSUE THREAD

**Issue by rexmas** [MindscapeHQ/raygun4apple#49]
Please add support for server-side swift / linux. Thank you.

**Comment by nikz** [comment]
hi @rexmas, what would you need in order for this to work?

**Comment by rexmas** [comment]
Please see this thread https://forums.swift.org/t/backtraces-in-swift/61736
for this library https://github.com/swift-server/swift-backtrace
though swift 5.9 has built in backtracing as shown in the readme of that github
and I believe this evolution proposal will improve the api in short time https://github.com/apple/swift-evolution/blob/main/proposals/0419-backtrace-api.md

overall at least to support swift 5.9 on the server, the raygun library needs to be completely implemented in standard swift (no objective-c) and rely on built-in backtracing for captures so it seems.

**Comment by sumitramanga** [comment]
Hi @rexmas ! 

Thank you for your request :) We really appreciate it when folk point out where our provider can be improved. 

We won't be taking on this in the near future as we have some awesome upcoming work but I can add it to our product feedback tool for our team to look into priortising. Feel free to also make noise via our forums as well - https://raygun.com/forums 

Thank you again,

Sumitra Manga
Team Lead, Senior Engineer @ Raygun

**Comment by sumitramanga** [comment]
Hi team, 

We've decided to close this issue out for now since this is an 'eventually we'll do but not for while' task. It’ll also come automatically with the change to Swift overall.

We haven't forgotten about it and will keep in mind! 

@rexmas - If you have anything else in mind, please do make us aware!

Thank you again,
Sumitra
