### ISSUE TITLE
Xcode 16.0 beta build fail

### ISSUE THREAD

**Issue by a-Mo7** [MindscapeHQ/raygun4apple#54]
Hi,

I am currently testing the Xcode 16.0 beta version but it fails to build my app which uses the raygun4apple package in version 2.0.1

I have the following error messages :

![Screenshot 2024-06-18 at 16 06 11](https://github.com/MindscapeHQ/raygun4apple/assets/104976454/e0da3aca-b1bd-4fc2-9390-9c4b7d1bcf9d)
![Screenshot 2024-06-18 at 16 06 27](https://github.com/MindscapeHQ/raygun4apple/assets/104976454/cd59b5cb-c7f0-4ebf-a3c0-f30002363492)
![Screenshot 2024-06-18 at 16 06 35](https://github.com/MindscapeHQ/raygun4apple/assets/104976454/9c243515-34d8-4ee1-8341-1d6ae96709fb)

The app builds great if I remove the package dependency.

I haven't seen any issue about it yet so I am asking it.

Could you help me ?

Regards,

Alexandre

**Comment by sumitramanga** [comment]
Hi @a-Mo7 , 

We're currently taking a look in your issue and will let you know how we get on

Cheers,
Sumitra

**Comment by sumitramanga** [comment]
Hi @a-Mo7 

My teammate has been kindly looking into this and has given us an update! They've spotted that there looks to be a few similar issues around: https://github.com/getsentry/sentry-cocoa/issues/4050

Something has changed with the underlying CrashHandler lib or the compiler version
We can also reproduce the issue and see a line change required to fix.

Will keep you posted! Thank you for your patience so far 

Cheers,
Sumitra

**Comment by a-Mo7** [comment]
Hi @sumitramanga 

Thank you very much for the answers. I will wait for the next beta to continue testing.

Regards,
Alexandre

**Comment by nikz** [comment]
Hi @a-Mo7, are you able to try this with the latest master at all and let me know if that helps?

**Comment by sumitramanga** [comment]
Hi @a-Mo7 We've gone ahead and put this out as an official release after noticing that this was affect our other provider relying on this provider. If you have any issues please do inform us! We'll gladly help out :) For now, I will close this issue

**Comment by a-Mo7** [comment]
Hi @sumitramanga,
I just tested now and it is working great ! Thanks
