### ISSUE TITLE
Xcode 16.1 beta build failed

### ISSUE THREAD

**Issue by stoska** [MindscapeHQ/raygun4apple#57]
<img width="1146" alt="Screenshot 2024-08-13 at 03 55 27" src="https://github.com/user-attachments/assets/8c7c3ab4-d004-4d44-a3aa-3acfddd00d98">

**Comment by sumitramanga** [comment]
Hi @stoska 

My apologies for the delayed response here. Appreciate the bump!

I've discussed this internally and we'd like to kindly ask to not use beta version with the provider for the moment please. We will let you know when we've got it fixed.

Thank you for your patience. I'll keep you posted.

Cheers,
Sumitra

**Comment by notapplicableio** [comment]
This is an issue in Xcode 16 (not beta).

**Comment by sumitramanga** [comment]
Hi @notapplicableio 

Thank you for bringing this to our attention!

We've bumped this to the team and will response back with an update once we have a further details.

Kind regards,
Sumitra

**Comment by Pallesen01** [comment]
Hi Everyone,

We've just released [raygun4apple 2.1.2](https://github.com/MindscapeHQ/raygun4apple/releases/tag/2.1.2) to solve this issue 😊
